server:
  port: 9997

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://193.112.38.174:3306/cms?useunicode=true;&characterEncoding=utf8
    username: root
    password: root

